import type { ThemeConfig, ThemePreset } from '../types/formatting.types.js';

const THEME_PRESETS: Record<ThemePreset, ThemeConfig> = {
  'corporate-blue': {
    name: 'corporate-blue',
    primaryColor: '#1F4E79',
    secondaryColor: '#2E75B6',
    accentColor: '#BDD7EE',
    headerBg: '#1F4E79',
    headerFg: '#FFFFFF',
    altRowBg: '#D6E4F0',
    borderColor: '#8DB4E2',
    fontFamily: 'Calibri',
    headerFontFamily: 'Calibri',
    headerFontSize: 12,
    bodyFontSize: 11,
  },
  'modern-green': {
    name: 'modern-green',
    primaryColor: '#2E7D32',
    secondaryColor: '#4CAF50',
    accentColor: '#C8E6C9',
    headerBg: '#2E7D32',
    headerFg: '#FFFFFF',
    altRowBg: '#E8F5E9',
    borderColor: '#A5D6A7',
    fontFamily: 'Segoe UI',
    headerFontFamily: 'Segoe UI',
    headerFontSize: 12,
    bodyFontSize: 11,
  },
  'elegant-gray': {
    name: 'elegant-gray',
    primaryColor: '#424242',
    secondaryColor: '#757575',
    accentColor: '#E0E0E0',
    headerBg: '#424242',
    headerFg: '#FFFFFF',
    altRowBg: '#F5F5F5',
    borderColor: '#BDBDBD',
    fontFamily: 'Garamond',
    headerFontFamily: 'Garamond',
    headerFontSize: 13,
    bodyFontSize: 11,
  },
  'bold-red': {
    name: 'bold-red',
    primaryColor: '#B71C1C',
    secondaryColor: '#E53935',
    accentColor: '#FFCDD2',
    headerBg: '#B71C1C',
    headerFg: '#FFFFFF',
    altRowBg: '#FFEBEE',
    borderColor: '#EF9A9A',
    fontFamily: 'Calibri',
    headerFontFamily: 'Calibri',
    headerFontSize: 12,
    bodyFontSize: 11,
  },
  'ocean-teal': {
    name: 'ocean-teal',
    primaryColor: '#00695C',
    secondaryColor: '#00897B',
    accentColor: '#B2DFDB',
    headerBg: '#00695C',
    headerFg: '#FFFFFF',
    altRowBg: '#E0F2F1',
    borderColor: '#80CBC4',
    fontFamily: 'Calibri',
    headerFontFamily: 'Calibri',
    headerFontSize: 12,
    bodyFontSize: 11,
  },
  'sunset-orange': {
    name: 'sunset-orange',
    primaryColor: '#E65100',
    secondaryColor: '#FB8C00',
    accentColor: '#FFE0B2',
    headerBg: '#E65100',
    headerFg: '#FFFFFF',
    altRowBg: '#FFF3E0',
    borderColor: '#FFCC80',
    fontFamily: 'Calibri',
    headerFontFamily: 'Calibri',
    headerFontSize: 12,
    bodyFontSize: 11,
  },
  'midnight-purple': {
    name: 'midnight-purple',
    primaryColor: '#4A148C',
    secondaryColor: '#7B1FA2',
    accentColor: '#E1BEE7',
    headerBg: '#4A148C',
    headerFg: '#FFFFFF',
    altRowBg: '#F3E5F5',
    borderColor: '#CE93D8',
    fontFamily: 'Calibri',
    headerFontFamily: 'Calibri',
    headerFontSize: 12,
    bodyFontSize: 11,
  },
  'nature-earth': {
    name: 'nature-earth',
    primaryColor: '#5D4037',
    secondaryColor: '#795548',
    accentColor: '#D7CCC8',
    headerBg: '#5D4037',
    headerFg: '#FFFFFF',
    altRowBg: '#EFEBE9',
    borderColor: '#BCAAA4',
    fontFamily: 'Georgia',
    headerFontFamily: 'Georgia',
    headerFontSize: 12,
    bodyFontSize: 11,
  },
  'minimal-white': {
    name: 'minimal-white',
    primaryColor: '#212121',
    secondaryColor: '#616161',
    accentColor: '#F5F5F5',
    headerBg: '#FAFAFA',
    headerFg: '#212121',
    altRowBg: '#FAFAFA',
    borderColor: '#E0E0E0',
    fontFamily: 'Arial',
    headerFontFamily: 'Arial',
    headerFontSize: 11,
    bodyFontSize: 10,
  },
  'dark-professional': {
    name: 'dark-professional',
    primaryColor: '#263238',
    secondaryColor: '#37474F',
    accentColor: '#78909C',
    headerBg: '#263238',
    headerFg: '#ECEFF1',
    altRowBg: '#ECEFF1',
    borderColor: '#90A4AE',
    fontFamily: 'Consolas',
    headerFontFamily: 'Consolas',
    headerFontSize: 12,
    bodyFontSize: 11,
  },
};

export function getThemeConfig(preset: ThemePreset): ThemeConfig {
  return THEME_PRESETS[preset] || THEME_PRESETS['corporate-blue'];
}

export function getAllThemes(): ThemePreset[] {
  return Object.keys(THEME_PRESETS) as ThemePreset[];
}

export function getThemePresets(): Record<ThemePreset, ThemeConfig> {
  return { ...THEME_PRESETS };
}
